spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: flight-api-service
          uri: lb://flight-api-service
          predicates:
            - Path=/api/v1/flights/**
        - id: hotel-api-service
          uri: lb://hotel-api-service
          predicates:
            - Path=/api/v1/hotels/**
        - id: nbp-api-service
          uri: lb://nbp-api-service
          predicates:
            - Path=/api/v1/currency/**
        - id: trip-api-service
          uri: lb://trip-api-service
          predicates:
            - Path=/api/v1/trips/**
        - id: user-api-service
          uri: lb://user-api-service
          predicates:
            - Path=/api/v1/users/**
server:
  port: 8080

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info