spring:
  application:
    name: hotel-api-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hotel_db?currentSchema=trip_planner}
    username: tp_admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: trip_planner

server:
  port: 8084

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info