spring:
  application:
    name: user-api-service

  datasource:
    url: jdbc:postgresql://postgres:5432/user_db?currentSchema=trip_planner
    username: tp_admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: trip_planner

server:
  port: 8087

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info