spring:
  application:
    name: trip-api-service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8081}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trip_db?currentSchema=trip_planner}
    username: tp_admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: trip_planner
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}


