version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Zawsze wrapper zamiast systemowego gradle
      - run: chmod +x ./gradlew
      - run: ./gradlew --version

      # Cache zależny od wrappera i głównego build.gradle (monorepo)
      - restore_cache:
          keys:
            - v2-gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
            - v2-gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v2-gradle-

      # Budowa całego monorepo
      - run: ./gradlew clean build --no-daemon

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
