spring:
  application:
    name: user-api-service
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8081}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_db?currentSchema=trip_planner}
    password: admin123
    username: tp_admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: trip_planner
        format_sql: 'true'

  mail:
    host: smtp.mailtrap.io
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    port: '2525'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'

app:
  config:
    support:
      email: support@test.com
    appname: Take Me
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}


