spring:
  application:
    name: gateway-service

  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8081}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONEhttp://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info