spring:
  application:
    name: discovery-service

  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8081}

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

